### ISSUE TITLE
Introduce store method `shouldDehydrate` to disable dehydration for a store

### ISSUE THREAD

**Issue by mridgway** [yahoo/dispatchr#44]
This method would allow stores to control whether they should dehydrate themselves on the server to be sent to the client. We have run into times where a store may have listened for an action, but we did not need the store to be rehydrated on the client. For instance, one-time-use server-only data.

In dispatchr's `dehydrate` method:
 * check if store implements `shouldDehydrate` method
   * if method exists, call it
     * if returns `true`, call dehydrate and return store's state
     * if returns `false`, ignore the store's state completely
   * if method does not exist:
     * always dehydrate (default to true)

**Comment by mdressman** [comment]
+1

sounds really useful to me

**Comment by mridgway** [comment]
We could also add a neat default `shouldDehydrate` method to the `BaseStore` that returns `true` only if `emitChange` has been called in the store.
