### ISSUE TITLE
require('util'), why?

### ISSUE THREAD

**Issue by ezequiel** [yahoo/dispatchr#52]
Dispatchr requires the node module `util`. Dispatchr seems to use only one function from `util`; `inherits`. 

However, `util` [doesn't actually implement `inherits`](https://github.com/defunctzombie/node-util/blob/master/util.js#L570) themselves. It simply re-exports the [`inherits` node module](https://www.npmjs.com/package/inherits).

So, why not avoid the middle man and use the `inherits` module instead? This will save us quite a few kilobytes.

**Comment by jedireza** [comment]
Looks like the [`node-util`](https://github.com/defunctzombie/node-util) and the built-in `util` are not exactly the same.

Here is the `util` lib from core:
https://github.com/joyent/node/blob/master/lib/util.js#L632-L642

Even in `0.10`:
https://github.com/joyent/node/blob/09b482886bdd3d863c3d4e7d71264eac0daaf9e1/lib/util.js#L554-L564

**Comment by ezequiel** [comment]
@jedireza 

Good point. They aren't exactly the same. It seems `node-util` hasn't been updated for a year.

After browserifying, I see the entire `util` module included in my bundle. Is this necessary?

**Comment by jedireza** [comment]
That doesn't sound desirable. IIRC Webpack has some optimizations we're taking advantage of to prevent this.

Here is our webpack config:
https://github.com/yahoo/fluxible.io/blob/master/Gruntfile.js#L123-L135

**Comment by 3den** [comment]
The 'util' lib it is not really necessary we can do inheritance without it.

**Comment by mridgway** [comment]
Agreed.

**Comment by mridgway** [comment]
I think the best course of action might be to use the `inherits` module that @ezequiel mentions. It's 100% compatible with node.

**Comment by 3den** [comment]
But `Object.create` is 100% with node and the browser also it won't add any extra code to webpack

**Comment by 3den** [comment]
take a look at the source code for https://github.com/joyent/node/blob/master/lib/util.js#L632-L642 it is just a wrapper for `MyClass.prototype = Object.create(ParentClass.prototype);`

**Comment by mridgway** [comment]
`inherits` also sets `MyClass._super` and ensures that `this.constructor` is set correctly. It's possible that downstream users are relying on these.

**Comment by 3den** [comment]
I think the best solution would be to use ES6 classes this way we get real classes, but if we cannot do that yet it would be good to minimize dependencies. 

The standard javascript way of Pseudo-classical inheritance is the one I sent on the PR and you can also see that example here => https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FObject%2Fcreate.

I never saw a case where the `super_`  was a good idea, would you ever use something like `this.constructor.super_.someMethod.call(this, args)`?

**Comment by 3den** [comment]
The `node/utils` file is 20kb but I am not sure how webpack optimizes it.

**Comment by luiztiago** [comment]
:+1: I was having that same issue of webpack it would be cool to remove that dependency.

**Comment by mridgway** [comment]
We are going to switch over to the `inherits` npm module for now until we start using ES6 classes.

**Comment by 3den** [comment]
ES6 classes?! That sounds awesome! :+1:

**Comment by 3den** [comment]
are we going to use ES6 modules too? http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by mridgway** [comment]
Yeah. We need to get the builds figured out first, but we will use babel to generate ES5 exports.

**Comment by mridgway** [comment]
This has been released in v0.3.0.

**Comment by equalbackslash** [comment]
this doesn't appear to be released, possibly someone merged back use of 'util' module. It is unclear from commit history

**Comment by mridgway** [comment]
You're totally right. Will look into this.
