### ISSUE TITLE
Throw an error if actionName passed to Dispatcher#dispatch is undefined

### ISSUE THREAD

**Issue by szimek** [yahoo/dispatchr#57]
I'm using constants instead of strings for action names to have them all in a single place as a documentation. An additional benefit could be that if I make a typo in a name of a constant, thus passing `undefined` value, `Dispatcher#dispatch` could throw an error making it much easier to spot such typos.

What do you think?

**Comment by mridgway** [comment]
Sounds reasonable to me. Want to PR it?

**Comment by szimek** [comment]
Sure. One question though - should it throw an error only on `undefined` or on all falsy values? In my use case it's enough to check for `undefined`, but I'm not sure if it makes sense to pass `null` or `""` as `actionName` as well.

**Comment by szimek** [comment]
@mridgway I've just created a PR for that https://github.com/yahoo/dispatchr/pull/58. Let me know if it's ok.

**Comment by mridgway** [comment]
Closed in #58
