### ISSUE TITLE
Tie together multiple actions of one async operation

### ISSUE THREAD

**Issue by dmitriiabramov** [yahoo/dispatchr#69]
this is more of a question/proposal

For example if we have an autosuggest widget for the contacts that dispatches `GET_CONTACTS_INVOKE` and `GET_CONTACTS_SUCCESS` actions as user types the name of the contact.

as user is typing something in the input it'll dispatch multiple actions:
`GET_CONTACTS_INVOKE`
`GET_CONTACTS_INVOKE`
`GET_CONTACTS_SUCCESS`
`GET_CONTACTS_SUCCESS`

and there is no way of identifying which success corresponds to which invoke action.

Right now we're generating tokens and pass them with the payload
```js
function actionCreator(context, payload) {
  var token = Math.random();
  context.dispatch('GET_CONTACTS_INVOKE', {token: token});
  apiClient.makeRequest().then(function(response) {
    context.dispatch('GET_CONTACTS_SUCCESS', {response: response, token: token});
  }).catch(function(error) {
    context.dispatch('GET_CONTACTS_FAILURE', {error: error, token: token});
  });
}
```

And on the stores side, we know how to group them together.

This is also important in the case of optimistic updates, because we need to know what we want to commit and what we want to rollback.

As an alternative and cleaner proposal, i was thinking, what if `context.dispatch()` had a pre-generated token in a closure every time the action creator function is invoked?
kind of like
```js
function DispatcherContext (dispatcher, context) {
  /* ... */
  var token = Math.random();
  this.dispatch = function(actionName, payload) {
    return DispatcherContext.prototype.dispatch.call(this, actionName, payload, token);
  }; 
}

```

so this action creator invoked twice will produce:
```js
function actionCreator(context, payload) {
  context.dispatch('INVOKE');
  async().then(function(response) {
    context.dispatch('SUCCESS', {response: response});
  });
};
```
will produce
```js
// => 'INVOKE', null, 123456
// => 'INVOKE', null, 098765
// => 'SUCCESS', {response: {}}, 098765
// => 'SUCCESS', {response: {}}, 123456
```

What are you thoughts on that?

**Comment by mridgway** [comment]
I think something like this would make sense as part of Fluxible, but not dispatchr. I have been thinking about doing something like this as well, maybe with each root level or component level `executeAction` shares the same identifier that gets passed to all dispatches. This way you'd also be able to correlate unrelated dispatches that are part of the same action chain.

Do you think you could move this issue to the Fluxible repo?

**Comment by dmitriiabramov** [comment]
@mridgway sure
https://github.com/yahoo/fluxible/issues/213
