### ISSUE TITLE
createStore does not expose store in dehydrated context.dispatcher.stores

### ISSUE THREAD

**Issue by gingur** [yahoo/dispatchr#70]
When creating stores and adding to a Fluxible application, the createStore method with a supplied `storeName` does not seem to register the store in the dehydrated object, whereas using `BaseStore` does?

**Comment by mridgway** [comment]
There shouldn't be a difference since `createStore` uses `BaseStore` under the hood. Make sure you are calling `emitChange` in your store's handlers so that dispatchr knows to dehydrate the store.

**Comment by gingur** [comment]
I think that is part of the issue, I was using `this.emit('change')`.  I also am using `rehydrate` to populate the store in my route action, where it sounds like I should instead execute a set state action to trigger a regular change event?

**Comment by mridgway** [comment]
Correct, you should only be calling `dispatch` in actions and have stores listen to these data events to update themselves. Stores should never be modified directly from an action.
