### ISSUE TITLE
Unable to affect state asynchronously from store, apply component `this` to handler function?

### ISSUE THREAD

**Issue by jeromecovington** [yahoo/dispatchr#72]
Within a react native app, I do not see a way to apply the component this context to the handler callback function.

```
// ExampleStore.js - store
'use strict';

var createStore = require('dispatchr/addons/createStore');
var Promise = require('bluebird');

var ExampleStore = createStore({
  storeName: 'ExampleStore',
  handlers: {
    GET_STATE: function () {
      var endpoint = '/endpoint';

      var promise = fetch(endpoint)
        .then(response => response.json());

      return Promise.resolve(promise)
        .then((data) => {
          // this.state is undefined...
          this.state.hasData = true;
          this.state.data = data;
          this.emitChange();
          // ...but can't access component setState(), either.
          this.setState({
            hasData: true,
            data: data
          });
        })
        .done();
    }
  }
});

module.exports = ExampleStore;

// Example.js - component
'use strict';

var React = require('react-native');
var ExampleStore = require('../../stores/ExampleStore');
var dispatcher = require('dispatchr').createDispatcher({
  stores: [ExampleStore]
});
var contextOptions = {};
var dispatcherContext = dispatcher.createContext(contextOptions);
var { View } = React;

var Example = React.createClass({
  getInitialState: function () {
    return {
      hasData: false,
      data: {}
    };
  },

  componentDidMount: function () {
    dispatcherContext.dispatch('GET_STATE', {});
  },

  render: function () {
    return (
      <View></View>
    );
  }
});

module.exports = Example;
```

It seems it may be desirable to have a way to apply the component `this` here - https://github.com/yahoo/dispatchr/blob/master/lib/Action.js#L67

**Comment by mridgway** [comment]
In Flux, the store should never have direct access to the component, just like in MVC the models should never reference the views. Any information that you need the store to have access to should be passed to the `dispatch()` method. The component should only be listening to changes from the store: `store.on('change', () => { this.setState(store.getState()); })`

**Comment by jeromecovington** [comment]
@mridgway - Am I misunderstanding Promises? It seems that I cannot return the object containing the updates for state, but just another Promise?

**Comment by mridgway** [comment]
Stores are `EventEmitters`, so you have the component add a change listener and when you call `this.emitChange()` it tells the listener that the store content has changed. Promises are not needed within stores since handlers are completely synchronous.

**Comment by jeromecovington** [comment]
All good points, and appreciated. Although you may notice in the example above that the data being set relies on a Promise being resolved from an asynchronous fetch. So in that case I do still think we need a way to affect state from within the then.

**Comment by jeromecovington** [comment]
All good points, and appreciated. Although you may notice in the example above that the data being set relies on a Promise being resolved from an asynchronous fetch. So in that case I do still think we need a way to affect state from within the `then`.

**Comment by jeromecovington** [comment]
Looking at this again, I think I see your point regarding `store.on('change', () => { this.setState(store.getState()); })`

But if you could please expand on that, as I don't immediately see a way to access `ShowsListStore` for `on()` or `getState()`

But overall I think the point is to fire the action from the component, allow the store to make its async fetch call and update an object property of the store with the desired state changes, and emit a change. Following that, the component would listen for the store's change and call `store.getState()`

So again, if all that makes sense, it is then a matter of being able to access `on` and `getState()` from `ShowsListStore`.

**Comment by jeromecovington** [comment]
I was just able to implement the above. Thanks for clearing up the issue, and not only reiterating why direct access to the component from the store is an antipattern, but clearly outlining a way out.

**Comment by mridgway** [comment]
Glad you figured it out @jeromecovington! Sorry for the delay in responses. If you have any other issues you may be able to get faster responses in our #fluxible channel on [Reactiflux](http://reactiflux.com/).
